[project]
name = "ai-agent-simulation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain",
    "langchain-openai",
    "openai",
    "pandas>=2.3.3",
    "pyyaml",
    "tiktoken",
    "transformers",
    "matplotlib",
    "tqdm",
]

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "langchain==0.2.14",
    "langchain-openai==0.1.16",
    "openai==1.59.6",
]
